### ISSUE TITLE
Error on model import most likely on material creation 

### ISSUE THREAD

**Issue by DartShinigami** [madwax/Blender_ioEDM#7]
Hi: I'm getting this error when trying to import for example the new AGM-88 
![Untitled-1](https://user-images.githubusercontent.com/30356375/98426048-6f898000-2065-11eb-914f-bcaac282c6f2.png)

After looking the code on the error i think is a material issue.

**Comment by madwax** [comment]
soz for the delay.

Umm thats odd why have ED added a new material type? Will need to see if they have added any more in. As for getting it to work I'm shocked its working with blender 2.79.  I've given up on this version and switched to working off tobi-be's BlenderEdmExporter which does not have an import function.  I'm also a loathed to touch anything import due to I've had a lot of people as me about ripping stuff off :(

**Comment by DartShinigami** [comment]
Is working perfect on most models, at least until now, BTW don't worry I don't do ripping my work is mostly skining and model study

**Comment by DartShinigami** [comment]
Confirmed the new material issue, I tried with various models that the plugin were able to open before and now it doesn't. So is a new material name that DCS added latter. BTW any news on the 2.80 update.

Best regards

**Comment by madwax** [comment]
Ok good to know.  I've not had the time to work on any thing DCS/blender related.  A little busy trying to get a DCS server management system together.  These no import in Tobi-be's which is the one to support +2.8. 

If you were hoping to import the models so you could use it to use blenders texture painting stuff you would get away with it on some models but most would be a big mess.  The importer does not handle the transforms of different sub objects propertly and it gets even worse when it comes to stuff based on bones.  You might be able to get a usable model for texturing/skining, via DirectX model capture tools?  It would be nice there were simple texture shells released so we could use them.

**Comment by DartShinigami** [comment]
Sorry is me again any news on fixing the error?????

**Comment by DartShinigami** [comment]
I have great news the plugin works in Blender 2.91 but has the same issue and now I can see more on the error data. So I was able to  pinpoint the issue with the extructure that read the file. Is there any reference or info on the data struct of DCS .EDM. Cause if you can't do it and with your permission maybe I can. I don't know python but I know C++. I hope there isn't is much difference????? 
![Untitled-1](https://user-images.githubusercontent.com/30356375/103489311-ad92ee00-4de1-11eb-9194-7acf0eada483.jpg)
